### ISSUE TITLE
Any plans to add this package to the Wally registry?

### ISSUE THREAD

**Issue by jon-love** [PysephRBX/ClientCast#7]
I'm sure you must know about [Wally](https://wally.run/). It'd be nice if this package was able to be installed and updated using Wally.

**Comment by Pyseph** [comment]
Hey - no, sadly ClientCast wasn't exactly designed to be a package in mind initially. ClientCast controls script behavior by injecting modules dynamically for easier UX, but as a result falls a bit outside of just being a package. In order to make ClientCast a package I'd have to rewrite the code to not automatically inject scripts, but rather to allow the developer able to manually require the module on both contexts.
